name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- master

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: Build
  displayName: 'Build application'
  jobs:
  - job: Build
    pool:
      name: 'Azure Pipelines'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Static Assets'
      inputs:
        SourceFolder: 'web-front-end'
        TargetFolder: 'publish_output/web-front-end'

    - task: DotNetCoreCLI@2
      displayName: 'Build function app project'
      inputs:
        projects: '**/*.csproj'
        arguments: '--output publish_output --configuration Release'

    - task: ArchiveFiles@2
      displayName: 'Archive function app files'
      inputs:
        rootFolderOrFile: 'publish_output/'
        includeRootFolder: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
- stage: Release
  displayName: 'Deploy application'
  jobs:
  - job: Deploy
    pool:
      name: 'Azure Pipelines'
    steps:
    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function App'
    - task: ExtractFiles@1
      displayName: 'Extract files '
      inputs:
        destinationFolder: 'web-front-end'
    - task: AzurePowerShell@4
      displayName: 'Azure PowerShell script: InlineScript'
      inputs:
        ScriptType: InlineScript
        Inline: |
        CD $ENV:SYSTEM_ARTIFACTSDIRECTORY\web-front-end\web-front-end
        
        $storageAccount = Get-AzStorageAccount -Name $ENV:StorageAccountName -ResourceGroupName $ENV:ResourceGroupName
        $ctx = $storageAccount.Context
        
        Get-ChildItem | Set-AzStorageBlobContent -Container '$web' -Context $ctx -Force -Properties @{ContentType = 'text/html'}
